### ISSUE TITLE
Is there a way to let PMV-107J send signal out of tire?

### ISSUE THREAD

**Issue by soyoeml** [xnk/pacific-tpms#4]
Hi,

This is not a issue. I just try to find a way to send LF signal to activate the TPMS sensor out of tire. I have four pacific PMV-107J sensors out of tire. But they don't send signal if they're not in the tire.  I know some TPMS scanners have a way to scan TPMS sensor. Could we send the signal as TPMS scanners do?

**Comment by xnk** [comment]
Hmm that's odd, all eight of my sensors sent signals periodically even out of the tires, at least every minute, but I read about some sensors that would only transmit if they detect a centrifugal force. Does your sensors transmit when in use, or could the batteries be empty? 

I did try to generate a LF signal into a small coil from a microcontroller to see if I could force mine to transmit immediately, but I was never successful - I'm not sure how powerful a signal they would need,but it seems to be a universal trigger signal around 200kHz.

**Comment by soyoeml** [comment]
I use a paper clamp to clamp the sensor and let it send data out successfully. Thanks.
